baseurl = "http://www.rogermolas.com"
DefaultContentLanguage = "en"
publishDir = "docs"
title = "Roger Molas"
theme = "beautifulhugo"
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true
[params]
    useChroma = true
[taxonomies]
   tag = "tags"
   category = "categories"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  title = "Roger Molas"
  subtitle = "Welcome to my site and this is the place where i collect my thoughts, works and findings to share with the public. "
  logo = "img/profile.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true

[Author]
  name = "Roger Molas"
  email = "contact@rogermolas.com"
  github = "rogermolas"
  twitter = "roger_molas"
  linkedin = "rogermolas"
  stackoverflow = "/users/592526/roger"

[[menu.main]]
    identifier = "ABOUT"
    name = "ABOUT"
    url = "about/"
    weight = 3

[[menu.main]]
    identifier = "PROJECTS"
    name = "PROJECTS"
    url = "projects/"
    weight = 2

[[menu.main]]
    parent = "ABOUT"
    name = "ME"
    url = "about/"
    weight = 1

#[[menu.main]]
#    parent = "ABOUT"
#    name = "TERMS OF SERVICE"
#    url = "policies/terms/"
#    weight = 2

[[menu.main]]
    parent = "ABOUT"
    name = "PRIVACY POLICY"
    url = "policies/privacy/"
    weight = 3


[[menu.main]]
    name = "BLOG"
    url = "blog/"
    weight = 1


